# Generated by Django 3.2.13 on 2023-09-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogadores', models.CharField(max_length=50)),
                ('frequencia', models.CharField(choices=[('Q', 'QUITE'), ('S', 'SOMETIMES'), ('F', 'FEW')], max_length=1)),
                ('posicao', models.CharField(choices=[('M', 'MEIO CAMPO'), ('Z', 'ZAGUEIRO'), ('A', 'ATACANTE'), ('G', 'GOLEIRO')], max_length=1)),
                ('gols', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.CharField(max_length=50)),
                ('time2', models.CharField(max_length=50)),
                ('situacao', models.CharField(max_length=70)),
                ('release_date', models.CharField(max_length=10)),
            ],
        ),
    ]
