# Generated by Django 3.2.13 on 2023-09-20 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbr', '0002_auto_20230912_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogos',
            old_name='jogos',
            new_name='times',
        ),
    ]
